module.exports={
    list:[{
        id:"001",
        name:'步惊去',
        avatar:'http://img.huizecdn.com/test/avatar1.jpg',
        type:'免费',
        des:'清华大学50周年同学聚会，开始报名啦！',
        images:['http://img.huizecdn.com/test/a1.jpg','http://img.huizecdn.com/test/b1.jpg','http://img.huizecdn.com/test/b2.jpg'],
        
        time:'2016-11-01',
        startTime:'2016-11-01',
        endTime:'2016-12-10',
        address:'广东深圳南山区海鲜楼南油分店 401包厢，旁边公交328，MM206，332，331，下公交往前走100米',
        num:'20',
        like:'12'
    },{
        id:"002",
        name:'唐僧',
        avatar:'http://img.huizecdn.com/test/avatar2.jpg',
        type:'￥130.00',
        des:'南山地区练习瑜伽',
        images:['http://img.huizecdn.com/test/a2.jpg','http://img.huizecdn.com/test/b3.jpg'],        
        time:'2016-11-01',
        startTime:'2016-11-01',
        endTime:'2016-12-10',
        address:'广东深圳南山区南油大',
        num:'20',
        like:'12'
    }
    ,{
        id:"003",
        name:'秦时明月',
        avatar:'http://img.huizecdn.com/test/avatar3.jpg',
        type:'￥50.00',
        des:'鹏程第一峰-深圳海拔第一高峰',
        images:['http://img.huizecdn.com/test/avatar3.jpg','http://img.huizecdn.com/test/a3.jpg','http://img.huizecdn.com/test/a4.jpg'],        
        time:'2016-11-01',
        startTime:'2016-11-01',
        endTime:'2016-12-10',
        address:'广东深圳龙岗区盐田区交界地区',
        num:'20',
        like:'12'
    }]
};